language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor_project.settings.test
script:
- coverage run --source=food_vendor_app manage.py test --settings=food_vendor_project.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: C+6+kdydXpfm81mBz/CkXvzkdLdXYy0KILDcV302tNGTHmfHQiT3CaeiDjkAjZeUTxzYHzkRjol8MctkCDglWeYkk026cByp8GNGVodbJPPtK5hvTsqI2BPVxTLo6GaNg4fp/kqXoFKL2uHX+fBrOPRZYl3wruOvCtERvLmdvV9bXjkZazOOnysmGvH4ekqRP2v9ct22boXDMUz6Fug5FbdQdI0AnJx4G9iuP0lEe/xh9i8A16OFle1/oqry+rB4Snh/xLjftGn8FKNPTxyIsBejnFR4hEvgOO16SkBxNOp+ZxGdpmegb6UU4xjce4/uXevszcM/vc3dcP4XFqHy+xM8nKyDbnzexxxNGyRGqljeYcLRnRqwTirHuj0r4ed+Kt83AFhbLhcoD5ZlVdPF2yZoXVx2IWc1vQlrMnHhbdy4Q0EQSMpW1s8Fy4YOqkZX8HKTzJMyUXzXOMjqacYGKxBaGuLuuXGQ6vxI5TWFXt1xt2IIjmKFMSVou3bxJOj19h64j1gqfANQs8ZVZIyDNKCs+IXx9HLIeWTwFzYPm0rViWvNhyDGR9keZ/v8+hdgtMUWBHQ0Xy27qL9NcP9QiCwyPpquoNZ5l5RBuy3Mrs1CTJ+Lm1pOx1HY6RyZw55oBHaUzpEwXviuy/EGWRTYJhEjek+xhgR1KOo+VAlrFwM=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
