language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor_project.settings.test
script:
- coverage run --source=food_vendor_app manage.py test --settings=food_vendor_project.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: 0etJJ5MUH84t1a613rM43LmDDqqb+yH3U881WioEzhpJNtLpCimlp+ZE3fYitJerD5gEUc47351b038BO77R69c3BgjqETZHOVvFg0fFJ+lkRMcaHWV6pngtIUvBPvuaczrioA5v39yLmvT8voHMvqtCqhEIUtcrguInkovN6cPXb/w9dpUKFq9YRWt2ZBE2tE69WDdP8qTo2LIUHZ/BSKOXrG44qFmcjZrx5L37LmVoTqdSR4G6SpkMqLqI9x1jWCQPmeTajktIlwKF/0C1x7kqFJIRIZJsk6J23hoEiL0twQO+gMCgxIUFaKzaoL0PE3/p35tr0V3YsEboegakV/JOzmZIUxo0BTKLLDLIVhZnLrSxIyrMYqYi9qFLTTyzG+pwbekaSc4HkII1dCrjpH4OELvZOLhXy8/DrHVAgzcuyPy6WY2NlEniG0pyYIfvxcJHaXt/A5+/M9YIwkbS1SkgePiGOe/7VvNCwYd3WGGDGpQTxwCxDoNwB2E5i0W9UZFZ71PRk6ywmQjdWdbj3DWEvX8MyPGnp3f95xxQUUCqZQ1bR0AtsvffTUWpCcYgBTIfOZj+bwQjWg2E19cw0fHEI3AUDR0ZmQ1czZyGGrn0m9IwZikk/X7yT+Nguef/NJpbPw2t/jWhy7vh2qrWx+L0WAdw83UcpfpWZjDF8HA=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
