language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor.settings.test
script:
- coverage run --source=api manage.py test --settings=food_vendor.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: AKdf1TbSQYqgua91DQQQLqS+Lp3WBfHbsMHMb7QyDTQDM6bVOLNusbhKJkMRwispY08sKc45skx1i0Hn9EarjNeMvjkXoC9z0k3b5UqZRIb37ZND+ssBe/FYBT0fiFKg2IArNxXnnj6MBn7xK1x4oQTH7fMIGrVJRun5jfBGz7/H/sTmp0YI4lpZsI8EJo4/qu6Wk/MyBSv/iNExl2WFE7pU2IR4TkiQa1/SxY+JHMU+wOXXjdiOTt5oCp9iCmqjeWahCwq0rHgaWCOBAZql9lYzN/vYPzO61V71RPLFRK9+RL9NY0ryJSAg5Eb+5OzVz4m1C7i6EudBVarqE1HZdUx9tTbud6Ec0UspJInfa0Ctvo+jy4y9aTVp7UZX6gHWK41XogiGbQXHZ76lHotLQU+iHf8wkH0BHg3AQKV8zNJh3VFh/5hsMrOnWChjUkp9YbXUiNogahGBqd0VWrOO2bZouxvnyQ2oGqv/J/uInjIyg96nDr+GBMAfcaHg34lhWUsoWWsgDbGieztk0GE8xBRoGagBFPRTVBpLV5cdEx1NV0Z86zEoBNfGj+SUr9Upz7A3OE7lUSSQUS7071R6xY0ifwzx3Cehiu1j+3xruFitEpNJYdSJy8WLffUAg6v3pjBJv1RvK2CcgEiNvBD3aaJ1+TQs0AoqhxqT8+cfhCg=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
