language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor.settings.test
script:
- coverage run --source=api manage.py test --settings=food_vendor.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: r0UagY0NC0CZySkB77yMFVzIuqBXjt5uzxulwilDAFu4VdkMi+R3Gqm+rW1vwjwwl4sggH34U2aM3DWRtYXxMPXVePKwDhXIKNdrIJ3YikOr5m0lcAzmgk+taAS5hrMwuXb5WYM8LL5wu1aClRYrlz3tgidpK7QrnsXjXmGXCBZXtsQNcyZFK1zql6OXfIHFC3cnUEK8wViTXdrs8CIdRPcOoqjoP+0/kd3vXqTHxUXev+czbNzcr9DrNi4prp3ZOXQeUlb+u/LvpKBMFz/WJUva7CRqjwSj3/+Th2CAo6VbChydHx0r4GUa4ltpng7/UtdN6Dbt2hLv02ORZRvXjjCRBX/pAnh/xRV946kymBouccmm7pCoDm6P6OmyTJ2irM+lhWExbSdK0Unz8pNjzCOnvVskrE0UFHehuzyVgCatZVeRuzDBaCnvzrMgd5g+KI7Jp2SnczN8+NTvSS2kuSOb/ccro3+dTvy7mhBLXfR+UxmmF3UuIbED9y7HyEcLW6dI42uXoe4+18CzDrxXU/JMqS/qQaLMhH/urUTEAdyI65Whi+9j0tfUSVTO1dznpsIY0xpxhvfj2OAxQtJb+5Di5FYV9ikx0oRJ0W11IdE319CQzBIGS3SGm+oNfGnEHx6qjM7le7xM+87f2FYH6LNOQUdR0uQrRXoY6LYHROI=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
