language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor_project.settings.test
script:
- coverage run --source=food_vendor_app manage.py test --settings=food_vendor_project.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: ig6gB5vc3QzzyRdsMjbA66ZIm5t2XWjSwxgEs+pRORzZWqfXTEL90qxnwen6kuQlg9duhPfUB1qOOm7Bvj0XX3pTR40pwlQA5Flb7M7j05XeNbDaw5TYdxI7FYUWP8N1ioHvqTJZqfQfegTEk9ZmKuIPbfEju/oeA5QwGpwnBQwPlZa+hYQPi9oWC3aZfXd0+RFrsVygbojB1qMw3smmtiMcX1pl6QXoP1ZN8Py1XTvDtI6VqQlt2xZiqVHu5cTP/JPh5Tmb9YCMIFMqzaE55+JfwkduAd2IFpVWAFO4SWY79q0uC5IAeTR9dbjBDiw+jrvZ+5HRP3DlyS9vmneaUY+SZN+5CkFbQR32iUT+olyRbjTB9aJChnwiEn+H73j/8Yb2bV8nUDn0q+AsBe9K7vKMYFhnkjHGqS7v+jKcrAcD4c1Bw4khMjuSAB7sWam17mofaVX+S91dBYuaPfNQDSiPXGF5Rmnh/ihs39nW7gVUQ432EfgcR8HKOxyRPJhB2Fu0LuWpxhnFEsG3jjpkDwEctSea/hJBXeJTgnJDqR85xgF1nwTN8ZiB96P7vPF52y3v2Uq/DzguD8Nq/VBosoMimK1HlfKWC3zstbf0jrKPrW//19ymnK9GIOVHFaIF+qtuWhs8ao54JR4qkbmcf/RS8dxmcuL3vyMSsHIbVgw=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
