language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor.settings.test
script:
- coverage run --source=api manage.py test --settings=food_vendor.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: Sj38UvD6P0x7Q3Sz4WH3+/pg+nziC4AcFHwIXcdEWnwiNe2dyWEMEuAUwuqOZd9pz2m/uC+0JXjfzbPgQnMzpBefOEqdMg0knyO/DfBnG1TcCNH5cGMJxYCFdjoiEdTHfyCFBKGOuwPqXPcI0trZ90AAqRhiLCWi9OwLBi5o6cyHrzbVk8Wd/Ve3eHslxS3dpdNXfwvneAgoLPx6O0ecRqyNJ7ldT7KVrbfbjUkNKxgvhFqiJWgrJoBzllrWRW6hn0cAqkHqTnj+faJe2E+MZjGZAgKw47773I5W5Ft6YeW0QqnZFnKzP7l9NpWeMtkxHnfm00JlXZpWDSypr9dy7SV5+eJpUomxxMtaDcOlhxSvABfhJ0JnyiXFH2Em4Fsr3SD+z3JcUKoYxEIkAwTZ2ZOtRS+Qay3RTZ2eV9y91Lg7u+Xf0cuoi2n6LYWAkq5CLwu3ScPH9wusWLAwADnLqiWUs6pqxO/ruXZ5FsUNdjPgkSqlZTWKxppB3MC1oEhPswXInx1PP309fUYXZC/EugUXrZkQ38K6fHPztFYhseL8Jj9DQFYiU/Bx0pfoCvQXuRivosS2f4aj77/vZsgJkrXyBTUE1TiU2djIsoqT5V5SmDcTBeBV24zSrVnuI1VQOGR2yjOpDLFKy4BF9fdaGLF2rNiRYcI4K9qjfHcKNaQ=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
