language: python
python:
- '3.6'
install:
- pip install -r requirements.txt
services:
- postgresql
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- python manage.py migrate --settings=food_vendor.settings.test
script:
- coverage run --source=api manage.py test --settings=food_vendor.settings.test
- flake8 .
after_success: coveralls
notifications:
  slack:
    secure: yT1V0G1fGCo6SSYaSUTCT+RMr/SGX2KNmuhopEF5hTm4gG8lC7o6HdxbLOjkWToB3sgkXN03YZbYyQPkGWCBUf2fpHA2sHSqA1rDFdEG4kyCyea9/8raWobF5SXBhK6SfDPP/J2IusBAriZOV85JrMne2gi/jctnqHEq3vY4c1AxhEkQBWenxXZjwvecRXuq1Yd7tDOBOxzZ34rwDoyvyqnTIghzmmPXk+GsK8PIgqNiIfuVyXQAuAUNJSj1O7SEmckGQm4Jwg/dn2rJXcFW/02KsibCAmCZNslniMvnmg5hY451KrqCGFqorY41oAwASOYulfyjnEsYoiItq2V1Jd9KXu2zU71wltMWUwO/hgm3OwtHf/os2FSE4giBTjVZ0r9S0uKOE+/aiUgp61gnv4MZ+owUip+TiMgpMDUZ+6h8YxT1T2tDtrRmG4X6D/H6hamPCVSJ0POunGRv0DfbR7qhbeOHP0zweQIC1w2mgaYT5WiW+0dPgczuZy3bRUX7TOYy4/azix8TaUedaCftZPXxi9Yjw3TpISq71+f4Aj7Hrw4gemvAWntBAKTbAimirxPj7mTb681axsmspyxbY5bUrmcOHAySmIXwrLP4sYDihUMhfW+Ijjv2ee01CD1Z6xbZ2E2HLC2XxsZW76zuO/04ftY+EVW0avtqYTIaFjQ=
deploy:
  provider: heroku
  api_key:
    secure: RW1HA7HmlXXLIwObYAITqrlwjR8glD5HH3du3KxsmdLdeqb+1BDcDwGCayQsPREnobi59TliQR9NlSYUvD8fq/LBIClNNNN5zF4GuKRWKwjxR6u1id12wQyi+qOTAUSrgNeLiS4was1+gDwKUgEYA61YhWF32e6SidRQnetSKjHjNGMOC8zAl9oaDruwJnm3x1D0JYVmTXMW0D/RulTnf8nxFxDQ90tROkV3SiCAz+8002PsHNODSQU1GEQDS+PtKiai/jfOIs4lE+z6Heu6X8zev7a+Y8x9mpFGhkXg9yOyomfFIbl5+xzaiLINf5zMj6kM6HVTe+Ct0+boK3ZIpa0ug8HcGNDzmrDV+CRwTfiOiFqDS66mIVkTxmhw8/Fh+wG66Qzh3RgdJHahbPjvY39zKpztP2qPnNbLy7Afx74eMhGxbs2mcPcqfdxJz0hLrpU6m+QuamL+owzsCpntNLIbkm4nc2zpSP4L807/3/Qx9m17vGFZl6VKqvi+FOALcYTqNRc1sNqZe9Y4n0W4AmreuKzd0Wjx3NxkqE62WXHZn7LayY00yxF/QCwMiOxSe8ydQpo4D15oBnRWZpVOcNI3rzvafOT3ZqtUlfHhIwRDblI5CJ6cCPUviyu9I0yhsKjfJYOnOtSdCbSV3IHkDyooUj1wPrYToTObSLHgdZE=
  app:
    master: food-vend-app
    staging: food-vend-app-staging
  run:
  - python manage.py migrate --noinput
