# Generated by Django 3.0.9 on 2020-10-11 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20201010_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(to='api.Meal'),
        ),
    ]
