# Generated by Django 3.0.9 on 2020-09-14 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
