# Generated by Django 3.0.9 on 2020-09-14 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0002_auto_20200914_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='vendor_id',
            new_name='vendor',
        ),
    ]
