# Generated by Django 3.0.9 on 2020-09-15 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0003_auto_20200914_1914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Days_Of_Occurence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_of_occurence', models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15)),
            ],
        ),
        migrations.AlterField(
            model_name='menu',
            name='days_of_occurence',
            field=models.CharField(max_length=15),
        ),
        migrations.RemoveField(
            model_name='menu',
            name='meals',
        ),
        migrations.AddField(
            model_name='menu',
            name='meals',
            field=models.ManyToManyField(related_name='meals', to='food_vendor_app.Meal'),
        ),
    ]
