# Generated by Django 3.0.9 on 2020-09-15 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0004_auto_20200915_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='days_of_occurence',
        ),
        migrations.AddField(
            model_name='menu',
            name='days_of_occurence',
            field=models.ManyToManyField(related_name='days', to='food_vendor_app.Days_Of_Occurence'),
        ),
    ]
