# Generated by Django 3.0.9 on 2020-09-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0005_auto_20200915_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='days_of_occurence',
            name='days_of_occurence',
            field=models.CharField(choices=[('MONDAY', 'Monday'), ('TUESDAY', 'Tuesday'), ('WEDNESDAY', 'Wednesday'), ('THURSDAY', 'Thursday'), ('FRIDAY', 'Friday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=15, unique=True),
        ),
    ]
