# Generated by Django 3.0.9 on 2020-09-15 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0006_auto_20200915_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_payment', to='food_vendor_app.Order'),
        ),
    ]
