# Generated by Django 3.0.9 on 2020-09-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food_vendor_app', '0007_auto_20200915_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='meal',
        ),
        migrations.AddField(
            model_name='order',
            name='meal',
            field=models.ManyToManyField(blank=True, to='food_vendor_app.Meal'),
        ),
    ]
